### ISSUE TITLE
Choose a license

### ISSUE THREAD

**Issue by flaiker** [kairet/kairet-cms#11]
http://choosealicense.com/licenses/

We should keep in mind that third party plugins propably want to license themselves as well (-> license compatibility / sublicensing).

@DerKaito @Paretos

**Comment by Paretos** [comment]
Hmm thats difficult question... @DerKaito which would you choose?

**Comment by flaiker** [comment]
Why not gpl v3?

**Comment by Paretos** [comment]
http://www.cnet.com/news/torvalds-no-gpl-3-for-linux/

you can take the advantages and disatvantage from this site @flaiker

**Comment by flaiker** [comment]
Which of these aspects do you think specifically applies to us @Paretos ?

**Comment by flaiker** [comment]
Seem like we have a draw, @DerKaito : You decide!

**Comment by DerKaito** [comment]
I would take glp v3

**Comment by Paretos** [comment]
So let's take gpl3 to continue our project.
